version: '3'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - PORT=3000

  database:
    image: postgres
    environment:
      - POSTGRES_USER=myUser
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=myDB
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
