version: '3'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      # Add other environment variables like database credentials, etc.

  database:
    image: postgres
    environment:
      - POSTGRES_USER=your_db_user
      - POSTGRES_PASSWORD=your_db_password
      - POSTGRES_DB=your_db_name
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
